### ISSUE TITLE
Add by ISBN doesn't bring data for some ISBN providers

### ISSUE THREAD

**Issue by andrelam** [seanboyce/ubiblio#11]
When trying to add some books by ISBN, I believe the code is using goob provider from isbnlib (the default one). However, for books from Brazil (for example, ISBN 9786586691627), not always the book is available correctly on Google Books.

```
> isbn_meta 9786586691627
Usage: isbn_meta ISBN [goob|openl|wiki] [bibtex|csl|csv|default|endnote|json|msword|opf|refworks|ris] [apikey]
  ...  or try with another service in list!
```

Trying with other providers also doesn't provide results:

```
> isbn_meta 9786586691627 openl
Usage: isbn_meta ISBN [goob|openl|wiki] [bibtex|csl|csv|default|endnote|json|msword|opf|refworks|ris] [apikey]
  ...  or try with another service in list!
```

But some providers result in valid data:

```
> isbn_meta 9786586691627 wiki
Type:      BOOK
Title:     Cabala
Author:    Gersom Scholem
ISBN:      9786586691627
Year:      2021
Publisher: Veneta
```

Is it possible to traverse each main provider (goob, then openl, then wiki) until a result is found? Or, better yet, create an option on the admin page with the priority for the provider search order?

Thanks!

**Comment by seanboyce** [comment]
That's a good idea, and quite easy to fix!

I'll probably add openl as the fallback. Then leave priority setting as a potential future addition.

**Comment by seanboyce** [comment]
OK! As this was a quick fix, I've pushed it directly to release. If you grab the latest version, it ought to just work.

Give it a try and let me know! I'll close the issue for now.

**Comment by andrelam** [comment]
You're fast! 🥇 
Tested and it's working good, although a bit slower due to additional queries for the other providers.
Thanks!
