### ISSUE TITLE
Option for Cover Images

### ISSUE THREAD

**Issue by tmnyhbs** [seanboyce/ubiblio#4]
Here with another feature request! 

As I am putting my library into Ubiblio, I can't help but wonder -- are cover images something that can be added? I tend to be a visual person, and I would love the option to either pull the image based on ISBN or, actually preferrably, to upload my own based on the exact copy I have of a book. 

Thank you for all the great work you have done on this so far!!!

**Comment by seanboyce** [comment]
When I wrote this software originally, it supported the ability to upload up to 16 images for each book. Files too, if you want (so it could manage e-books too).

I plan to add back the ability to upload images and other files, after I handle some boring but essential stuff like database export / import.

I intend for this application to remain text-only by default though. The add-by-ISBN feature can actually grab cover images automagically, but I disabled it. In other words, any images will be "opt-in", never automatic -- it will only use e.g. cover images if you choose to upload them.

Check back in a few weeks!

**Comment by seanboyce** [comment]
Hello again!

I've added cover image support in the dev branch. If you would like to help me test it out, please report any bugs! I plan to test it over the week and then deploy to production.

Note that you'll need to manually move your DB file over to the new system. I've added backup management too, so for future versions upgrading should be smoother.

**Comment by seanboyce** [comment]
This has been added in the latest release now! Note that the new backup feature only covers the DB for now.

So if you want to backup images, then you have to do that manually. An automatic solution is planned for the next release.
